### ISSUE TITLE
[Estudo] Explorar o algoritmo de Naive Bayes para análise de sentimentos

### ISSUE THREAD

**Issue by elvinmatheus** [elvinmatheus/mandacaru.dev-ibiapaba-cdd#14]

**Comment by elvinmatheus** [comment]
# Resultados obtidos

Após estudo do algoritmo naive bayes, percebemos que o algoritmo é bom para tais situações...

**Comment by Ingenieco** [comment]
## O algoritmo Naive Bayes

São algoritmos de classificação de aprendizagem automatizado. São uma técnica de classificação chamada teorema de bayes
São algoritmos inocentes o "naive" onde as variáveis preditoras são independentes entre elas. Ou seja, a presença de uma determinada caraterística (variável) não está relacionada com outra.
Esta técnica utiliza a probabilidade após a ocorrência de um evento, dadas umas probabilidades de eventos anteriores.
O algoritmo segue um conjunto de passos:

1.	Converter o conjunto de dados em uma tabela de frequências
2.	Criar uma tabela a de probabilidade calculando as correspondentes que ocorram os diversos eventos
3.	A equação de Naive Bayes é usada para calcular a probabilidade posterior de cada classe.
4.	A classe com a probabilidade após mais alta é o resultado da predição.

Têm pontos fortes e débeis e fortes, por exemplo, os fortes são a predição de classes no caso de problemas binários e múltiplas. Se os eventos são presumivelmente independentes, o algoritmo tem um comportamento melhor que outros modelos.
No caso das predições débeis, tem pobreza nos estimadores, a presunção de independência não é um reflexo de como são os dados no mundo real.
Quando o conjunto de dados tem caraterísticas que não haviam sido observadas no conjunto de treinamento, o modelo fornece uma probabilidade de zero e fica inútil realizar predições.
https://joaoclaudionc.medium.com/o-algoritmo-naive-bayes-descri%C3%A7%C3%A3o-e-implementa%C3%A7%C3%A3o-em-python-35757ade6b36
https://medium.com/datos-y-ciencia/algoritmos-naive-bayes-fudamentos-e-implementaci%C3%B3n-4bcb24b307f
